In [2]:
import numpy as np
import copy
import imp
import network
import mynet
import random
random.seed(0) # ensure random values are always the same
np.random.seed(0)
imp.reload(network)
imp.reload(mynet)

np.set_printoptions(precision=2)
def printValues(listVals):
   for i in range(len(listVals)):
        print(listVals[i])
        print()
        
        
sizes = [2,3,1]
sizes = [2,3,2]
#net = network.Network(sizes)
net = mynet.Network(sizes)
print("num_layers = {}".format(net.num_layers))
print("net.sizes: (list of " + str(type(net.sizes[0])) + "):")
print(net.sizes)

print("net.weights: (list of " + str(type(net.weights[0])) + "):")
printValues(net.weights)

print("net.biases: (list of " + str(type(net.biases[0])) + "):")
printValues(net.biases)
#print(net.biases)

num_layers = 3
net.sizes: (list of <class 'int'>):
[2, 3, 2]
net.weights: (list of <class 'numpy.ndarray'>):
[[-0.98  0.95]
 [-0.15 -0.1 ]
 [ 0.41  0.14]]

[[1.45 0.76 0.12]
 [0.44 0.33 1.49]]

net.biases: (list of <class 'numpy.ndarray'>):
[[1.76]
 [0.4 ]
 [0.98]]

[[2.24]
 [1.87]]



## calculating activations (feed forward)
$$a = \sigma(w*a + b)$$

In [3]:
#from mynet import sigmoid
# calculate activations of layer 1 given input layer 0

# manually set weights for connections between layers 0 and 1
net.weights[0]=np.array([[-0.3, -0.01], [2.94,-0.88], [0.91, -1.85]])
# same for layers 1 and 2
net.weights[1]=np.array([[1.62, 1.21, 0.95], [-0.19, -0.68, 0.61]])

# manually set biases:
net.biases[0]=np.array([[-0.25], [-0.34], [0.21]])
net.biases[1]=np.array([[-0.88], [0.47]])

a0 = np.array([[4],[7]])

print("weights = ")
print(net.weights[0])
print("initial a")
print(a0)
print("biases = ")
print(net.biases[0])
print("w*a:")
a = np.dot(net.weights[0],a0)
print(a)
print("w*a+b = ")
a += net.biases[0]
print(a)
print("sigmoid(w*a+b)")
print(net.sigmoid(a))

print("true result")
print(net.feedforward(a0))

weights = 
[[-0.3  -0.01]
 [ 2.94 -0.88]
 [ 0.91 -1.85]]
initial a
[[4]
 [7]]
biases = 
[[-0.25]
 [-0.34]
 [ 0.21]]
w*a:
[[-1.27]
 [ 5.6 ]
 [-9.31]]
w*a+b = 
[[-1.52]
 [ 5.26]
 [-9.1 ]]
sigmoid(w*a+b)
[[1.79e-01]
 [9.95e-01]
 [1.12e-04]]
true result
([array([[0.],
       [0.]]), array([[-1.52],
       [ 5.26],
       [-9.1 ]]), array([[ 0.61],
       [-0.24]])], [array([[4],
       [7]]), array([[1.79e-01],
       [9.95e-01],
       [1.12e-04]]), array([[0.65],
       [0.44]])])


In [4]:
sizes = [4,2,3]
net = network.Network(sizes)

print("original weights: (list of " + str(type(net.weights[0])) + ")")
print(type(net.weights[0]))
printValues(net.weights)
print("shape of net.weights[0]: " + str(net.weights[0].shape))

# manually set weights for connections between layers 0 and 1
net.weights[0]=np.array([[0.1, 0.2, 0.3, 0.4], [1.1,1.2,1.3,1.4]])
# same for layers 1 and 2
net.weights[1]=np.array([[0.5, -0.5], [0.6, -1], [0.7, -2]])

# manually set biases as well
net.biases[0] = np.array([[1.0], [1.0]])
net.biases[1] = np.array([[2.0], [2.0], [2.0]])

print("\nnew weights:")
printValues(net.weights)

print("new biases: (list of " + str(type(net.biases[0])) + ")")
print(type(net.biases[0]))
printValues(net.biases)

# make a copy of this network using my class instead
mine = mynet.Network(sizes)
mine.weights = copy.deepcopy(net.weights)
mine.biases = copy.deepcopy(net.biases)
mine.sizes = copy.deepcopy(net.sizes)

original weights: (list of <class 'numpy.ndarray'>)
<class 'numpy.ndarray'>
[[ 0.86 -0.74  2.27 -1.45]
 [ 0.05 -0.19  1.53  1.47]]

[[ 0.15  0.38]
 [-0.89 -1.98]
 [-0.35  0.16]]

shape of net.weights[0]: (2, 4)

new weights:
[[0.1 0.2 0.3 0.4]
 [1.1 1.2 1.3 1.4]]

[[ 0.5 -0.5]
 [ 0.6 -1. ]
 [ 0.7 -2. ]]

new biases: (list of <class 'numpy.ndarray'>)
<class 'numpy.ndarray'>
[[1.]
 [1.]]

[[2.]
 [2.]
 [2.]]

