In [692]:
import numpy as np
import copy
import imp
import network
import mynet
imp.reload(network)
imp.reload(mynet)

def printValues(listVals):
   for i in range(len(listVals)):
        print(listVals[i])
        print()

In [693]:
sizes = [4,2,3]
net = network.Network(sizes)

print("original weights: (list of " + str(type(net.weights[0])) + ")")
print(type(net.weights[0]))
printValues(net.weights)
print("shape of net.weights[0]: " + str(net.weights[0].shape))

# manually set weights for connections between layers 0 and 1
net.weights[0]=np.array([[0.1, 0.2, 0.3, 0.4], [1.1,1.2,1.3,1.4]])
# same for layers 1 and 2
net.weights[1]=np.array([[0.5, -0.5], [0.6, -1], [0.7, -2]])

# manually set biases as well
net.biases[0] = np.array([[1.0], [1.0]])
net.biases[1] = np.array([[2.0], [2.0], [2.0]])

print("\nnew weights:")
printValues(net.weights)

print("new biases: (list of " + str(type(net.biases[0])) + ")")
print(type(net.biases[0]))
printValues(net.biases)

# make a copy of this network using my class instead
mine = mynet.Network(sizes)
mine.weights = copy.deepcopy(net.weights)
mine.biases = copy.deepcopy(net.biases)
mine.sizes = copy.deepcopy(net.sizes)

original weights: (list of <class 'numpy.ndarray'>)
<class 'numpy.ndarray'>
[[0.52292845 0.67581768 0.64377182 0.43170139]
 [0.9359769  0.56116772 0.37938211 0.99719719]]

[[0.17844689 0.2052944 ]
 [0.05782458 0.71445456]
 [0.03332703 0.61467988]]

shape of net.weights[0]: (2, 4)

new weights:
[[0.1 0.2 0.3 0.4]
 [1.1 1.2 1.3 1.4]]

[[ 0.5 -0.5]
 [ 0.6 -1. ]
 [ 0.7 -2. ]]

new biases: (list of <class 'numpy.ndarray'>)
<class 'numpy.ndarray'>
[[1.]
 [1.]]

[[2.]
 [2.]
 [2.]]



In [694]:
# test my code vs network.py

def train(x, y):
    rate = 0.1
    mine_b, mine_w = mine.backprop(x, y)
    mine.biases = [b - rate * db for b, db in zip(mine.biases, mine_b)]
    mine.weights = [w - rate * dw for w, dw in zip(mine.weights, mine_w)]

# training data lists
X = []
Y = []
X.append(np.array([[1], [2], [3], [4]]))
Y.append(np.array([[0.0], [1.0], [0.0]]))

X.append(np.array([[-1], [-4], [-99], [0.3]]))
Y.append(np.array([[0.333], [0.333], [0.333]]))

X.append(np.array([[7.0], [4], [9], [6]]))
Y.append(np.array([[0], [0], [1.0]]))

print("testing forward pass evaluation...")
assert(np.allclose(net.feedforward(X[0]), mine.evaluate(X[0])))

print("testing backprop function...")
nabla_b, nabla_w = net.backprop(X[0], Y[0])
mine_b, mine_w = mine.backprop(X[0], Y[0])
# https://stackoverflow.com/a/30773738
assert(all([np.allclose(nb, mb) for nb, mb in zip(nabla_b, mine_b)]))
assert(all([np.allclose(nw, mw) for nw, mw in zip(nabla_w, mine_w)]))

print("testing updateMiniBatch function...")
# test with a batch size of 1
net.update_mini_batch([(X[index], Y[index])], 0.25)
mine.updateMiniBatch([(X[index], Y[index])], 0.25)
assert(all([np.allclose(b, mb) for b, mb in zip(net.weights, mine.weights)]))
assert(all([np.allclose(w, mw) for w, mw in zip(net.biases, mine.biases)]))

X = X[1:3]
Y = Y[1:3]

batch = [(x,y) for x,y in zip(X,Y)]
iterations = 1000
for i in range(iterations):
    index = i % len(X)
    net.update_mini_batch(batch, 0.25)
    mine.updateMiniBatch(batch, 0.25)
    
# test weights and biases were updated to same values
assert(all([np.allclose(b, mb) for b, mb in zip(net.weights, mine.weights)]))
assert(all([np.allclose(w, mw) for w, mw in zip(net.biases, mine.biases)]))

print("\nfinal outputs on training data:")
# now test:
for x,y in zip(X, Y):
    assert(np.allclose(net.feedforward(x), mine.evaluate(x)))
    print(mine.evaluate(x))
    
print("\nfinsihed all tests!")

testing forward pass evaluation...
testing backprop function...
testing updateMiniBatch function...

final outputs on training data:
[[0.32718759]
 [0.32832133]
 [0.36315287]]
[[0.03581287]
 [0.03283559]
 [0.92782885]]

finsihed all tests!
